# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95c213384f5dc97ee98c0fd9119e3ca27dc687c396a52dd4c5c5ec4e01a4b5188a7dbaff4ff720b5f76fe240a8f30a374ed9b5bd844183d435036152fd101951

test:
  secret_key_base: 0e0113625ac7db1c57defa5361d4525e0fde70885659261acd5a61ad9f168e57e1aca3688f89952a1158f1541fb2a4176e416c98ab949bb9fbbef9335c0af473

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
